[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pc2img"
description = "Short description of DeSpAn"
requires-python = "~=3.11"
keywords = ["one", "two"]
license = {text = "Proprietary"}
authors = [
	{name = "Nicholas Meyer"},
	{email = "meyernic@ethz.ch"},
]
dynamic = ["version", "readme"]
classifiers = [
	"Programming Language :: Python :: 3"
]
dependencies = [
	"pchandler ~= 0.4",
	"numpy ~= 1.24",
	"imageio ~= 2.31",
	"joblib ~= 1.3",
	"Pillow ~= 10.0",
	"scipy ~= 1.11",
	"typing-extensions ~= 4.9",
	"tifffile[all] ~= 2024.1",
	"opencv-python ~= 4.0",
#	"cupy-cuda12x ~= 13.2",
#	"PyYAML ~= 6.0",
#	"omegaconf ~= 2.2",
#	"hydra-core ~= 1.3",
]

[tool.setuptools.dynamic]
#version = {attr = "pc2img.__version__"}
readme = {file = ["README.rst"]}

[tool.setuptools_scm]
write_to = "src/pc2img/_version.py"
local_scheme = "no-local-version"
version_scheme = "post-release"

[project.urls]
homepage = "https://gseg.igp.ethz.ch/"
documentation = "https://google.com"
#repository = "https://gseg-ethz.github.com/DeSpAn"

#[project.scripts]
#DeSpAn = "DeSpAn.cli:main"

[project.optional-dependencies]
doc = ["sphinx ~= 5.1"]
dev = ["black ~= 22.10"]
cuda12 = [  # Issue with `--extra-index-url=https://pypi.nvidia.com`
	"cudf-cu12 ~= 24.8",
	"cuml-cu12 ~= 24.8",
	"cupy-cuda12x ~= 13.0",
]
cuda11 = [ # Check version numbers
	"cudf-cu11 ~= 24.8",
	"cuml-cu11 ~= 24.8",
	"cupy-cuda11x ~= 13.0",
]
