[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pc2img"
description = "Software to convert point clouds to images with various image representations."
requires-python = "~=3.11"
keywords = ["point cloud", "images", "lidar", "projection", "geospatial"]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
	{name = "Nicholas Meyer", email = "meyernic@ethz.ch"},
]
dynamic = ["version", "readme"]
classifiers = [
	"Programming Language :: Python :: 3"
]
dependencies = [
	"pchandler",
	"numpy ~= 1.24",
	"imageio ~= 2.31",
	"joblib ~= 1.3",
	"Pillow ~= 10.0",
	"scipy ~= 1.11",
	"tifffile[all] ~= 2024.1",
	"matplotlib ~= 3.7",
	"scikit-learn ~= 1.3",
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}

[tool.setuptools_scm]
write_to = "src/pc2img/_version.py"
local_scheme = "no-local-version"
version_scheme = "post-release"

[project.urls]
homepage = "https://gseg.igp.ethz.ch/"
repository = "https://github.com/gseg-ethz/pc2img/tree/main"


[project.optional-dependencies]
doc = ["sphinx ~= 5.1"]
dev = ["black ~= 22.10"]
cuda12 = [  # Issue with `--extra-index-url=https://pypi.nvidia.com`
	"cudf-cu12 ~= 24.10",
	"cuml-cu12 ~= 24.10",
	"cupy-cuda12x ~= 13.0",
]
cuda11 = [ # Check version numbers
	"cudf-cu11 ~= 24.10",
	"cuml-cu11 ~= 24.10",
	"cupy-cuda11x ~= 13.0",
]
